---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - namespace: reloader
    name: reloader
    releaseName: reloader
    repo: https://stakater.github.io/stakater-charts
    includeCRDs: true
    valuesFile: values.yaml
    version: 2.2.6
