---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - namespace: arc-runners
    name: gha-runner-scale-set
    releaseName: arc-runner-set
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    includeCRDs: true
    valuesFile: values.yaml
    version: 0.13.0

resources:
  - rbac.yaml
  - secret.yaml
