---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: cyberchef-ingress
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  tls:
    secretName: home-lungoo-de-tls
  routes:
    - match: Host(`cyberchef.home.lungoo.de`)
      kind: Rule
      services:
        - name: cyberchef-service
          port: 80
