---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

images:
  - name: ghcr.io/gchq/cyberchef
    newTag: 10.19.4@sha256:a2bfe382b2547bdd0a3d0523b9a6b85fab833c56bcec86d600ba6266910b533e

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
