---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - namespace: external-secrets
    name: external-secrets
    releaseName: external-secrets
    repo: https://charts.external-secrets.io
    includeCRDs: true
    valuesFile: values.yaml
    version: 1.2.0

resources:
  - issuer.yaml
  - certificates.yaml
