---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - namespace: longhorn-system
    name: longhorn
    releaseName: longhorn
    repo: https://charts.longhorn.io
    includeCRDs: true
    valuesFile: values.yaml
    version: 1.10.1

resources:
  - ingress.yaml
  - cifs-secret.yaml
