---
preUpgradeChecker:
  jobEnabled: false

persistence:
  defaultClassReplicaCount: 3

defaultBackupStore:
  backupTarget: cifs://10.0.20.10/longhorn
  backupTargetCredentialSecret: cifs-secret

defaultSettings:
  createDefaultDiskLabeledNodes: true
  defaultDataPath: /longhorn
  storageReservedPercentageForDefaultDisk: "0"
