---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - namespace: arc-system
    name: gha-runner-scale-set-controller
    releaseName: arc
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    includeCRDs: true
    valuesFile: values.yaml
    version: 0.13.0
