---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: actual-budget-ingress
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  tls:
    secretName: home-lungoo-de-tls
  routes:
    - match: Host(`actual-budget.home.lungoo.de`)
      kind: Rule
      services:
        - name: actual-budget-service
          port: 5006
