---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-lungoo-de
  namespace: cert-manager
spec:
  secretName: home-lungoo-de-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "argocd,longhorn-system,prod,traefik"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "argocd,longhorn-system,prod,traefik"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.home.lungoo.de"
  dnsNames:
    - "home.lungoo.de"
    - "*.home.lungoo.de"
