---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - namespace: cert-manager
    name: cert-manager
    releaseName: cert-manager
    repo: oci://quay.io/jetstack/charts
    includeCRDs: true
    valuesFile: values.yaml
    version: v1.19.2
  - namespace: cert-manager
    name: cert-manager-webhook-netcup
    releaseName: cert-manager-webhook-netcup
    repo: https://aellwein.github.io/cert-manager-webhook-netcup/charts/
    includeCRDs: true
    version: 1.0.35

resources:
  - netcup-secret.yaml
  - issuer.yaml
  - certificates.yaml
