---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netcup-secret
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: customer-number
      remoteRef:
        key: "22a7efac-5b75-411d-9cbc-b33800e93681"
    - secretKey: api-key
      remoteRef:
        key: "4cc75b59-8b4d-4b93-b6b9-b33800e95846"
    - secretKey: api-password
      remoteRef:
        key: "20130493-c8c5-4917-a30f-b33800e96d57"
