---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/argoproj/argo-cd/manifests/cluster-install?ref=v3.2.3
  - ingress.yaml
  - core-components.yaml
  - prod-apps.yaml

patches:
  - path: argocd-cm-patch.yaml
  - path: argocd-cmd-params-cm-patch.yaml
