---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - namespace: reflector
    name: reflector
    releaseName: reflector
    repo: https://emberstack.github.io/helm-charts
    includeCRDs: true
    valuesFile: values.yaml
    version: 9.1.45
