---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

images:
  - name: ghcr.io/traefik/whoami
    newTag: v1.11.0@sha256:200689790a0a0ea48ca45992e0450bc26ccab5307375b41c84dfc4f2475937ab

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
