---
name: Ansible lint
on:
  pull_request:
    branches:
      - main
    paths:
      - "ansible/**"

permissions:
  contents: read
  pull-requests: read

jobs:
  changed-ansible-files:
    runs-on: arc-runner-set
    name: Find changed ansible-files
    container:
      image: alpine/k8s:1.35.0@sha256:b01ed7ee5807e1abce433fba29447595b6157851054a649c2aafd6c22a3aa16c
    outputs:
      ansible-files_matrix: ${{ steps.changed-ansible-files.outputs.ansible-files_matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          matrix: true
          dir_names: false

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Filter ansible-files matrix
        id: changed-ansible-files
        run: |
          CHANGED_FILES='${{ steps.changed-files.outputs.all_changed_files }}'
          ANSIBLE_FILES=$(echo $CHANGED_FILES | jq -r '.[] | select(startswith("ansible"))' | jq -R . | jq -sc .)
          echo "Filtered matrix: $ANSIBLE_FILES"
          echo ansible-files_matrix=$ANSIBLE_FILES >> $GITHUB_OUTPUT
        shell: bash

  validation:
    runs-on: arc-runner-set
    name: Validate ${{ matrix.ansible-file }}
    needs: changed-ansible-files
    container:
      image: pipelinecomponents/ansible-lint:0.79.11@sha256:c0d862eca7d64fb581d321acea1dbb846af8903ff4799624f89ef9263038d5c5
    strategy:
      matrix:
        ansible-file: ${{ fromJSON(needs.changed-ansible-files.outputs.ansible-files_matrix) }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: ansible-lint
        run: |
          ansible-lint ${{ matrix.ansible-file }}

  validation-result:
    runs-on: arc-runner-set
    name: Validation result
    needs: validation
    container:
      image: alpine/k8s:1.35.0@sha256:b01ed7ee5807e1abce433fba29447595b6157851054a649c2aafd6c22a3aa16c
    steps:
      - name: Set status based on build
        run: |
          if [ "${{ needs.validation.result }}" == "success" ]; then
            echo "Validation succeeded."
          else
            echo "Validation failed."
            exit 1
          fi
