---
name: Workflow lint
on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/**"

permissions:
  contents: read
  pull-requests: read

jobs:
  changed-workflows:
    runs-on: arc-runner-set
    name: Find changed workflow files
    container:
      image: alpine/k8s:1.35.0@sha256:b01ed7ee5807e1abce433fba29447595b6157851054a649c2aafd6c22a3aa16c
    outputs:
      workflows_matrix: ${{ steps.changed-workflows.outputs.workflows_matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v47
        with:
          matrix: true
          dir_names: false

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

      - name: Filter workflows matrix
        id: changed-workflows
        run: |
          CHANGED_FILES='${{ steps.changed-files.outputs.all_changed_files }}'
          WORKFLOWS=$(echo $CHANGED_FILES | jq -r '.[] | select(startswith(".github"))' | jq -R . | jq -sc .)
          echo "Filtered matrix: $WORKFLOWS"
          echo workflows_matrix=$WORKFLOWS >> $GITHUB_OUTPUT
        shell: bash

  validation:
    runs-on: arc-runner-set
    name: Validate ${{ matrix.workflow }}
    needs: changed-workflows
    container:
      image: pipelinecomponents/yamllint:0.35.9@sha256:3e9eb9bef568b904d9222e9174a1490f4e015aef3d61e7d3e56f60035e517b79
    strategy:
      matrix:
        workflow: ${{ fromJSON(needs.changed-workflows.outputs.workflows_matrix) }}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: yamllint
        run: |
          yamllint -c _yamllint.yaml ${{ matrix.workflow }}

  validation-result:
    runs-on: arc-runner-set
    name: Validation result
    needs: validation
    container:
      image: alpine/k8s:1.35.0@sha256:b01ed7ee5807e1abce433fba29447595b6157851054a649c2aafd6c22a3aa16c
    steps:
      - name: Set status based on build
        run: |
          if [ "${{ needs.validation.result }}" == "success" ]; then
            echo "Validation succeeded."
          else
            echo "Validation failed."
            exit 1
          fi
